### PR TITLE
Make the app installable with pip

### PR DESCRIPTION
**Pull request by JanLikar**

### CODE REVIEW

**Comment by learnbyexample** [comment]
Thanks for the PR.

I have a few suggestions and questions:

* Is `.gitignore` needed since `user_progress.json` isn't checked in anyway?
* `. textual_apps/bin/activate` — I'd suggest to use `source` instead of `.`
* `version='0.0.1'` — `1.0.0` would be better since I consider this version as complete
* `author='learnbyexample'` — I'd prefer my name 'Sundeep Agarwal'

**Comment by learnbyexample** [comment]
Hey,

This gives an error since `questions.json` wasn't found. It works if I `cd` into `src/cli-exercises/CLI-Exercises` directory and then use `cli_exercises`.

And I think it will cause issues due to the files used for input questions and expected output. So, the code has to be run from within the `CLI-Exercises` folder.

So, I've reverted the merge for now. Let me know if it is possible to handle changing to the `CLI-Exercises` folder as well in the setup instructions.

I might be away for a few days, so expect delayed response.

**Comment by JanLikar** [comment]
I'm sorry, I only tested inside the same directory, which is not how this would generally be used...

In addition to the error you pointed out, there's also something else I forgot to account for: user_progress.json would need to be placed to a global location (probablly `~/.local/share` on Linux).

**Comment by learnbyexample** [comment]
No problem, at least it has given me something to consider for future versions :+1:

**Pull request merged**
